CREATE TABLE USER(
	ID varchar(50) PRIMARY KEY,
    PW varchar(50),
    PWHINT VARCHAR(100),
    HP varchar(50),
    ADDRESS VARCHAR(100),
    NAME VARCHAR(100),
    NICKNAME VARCHAR(100),
    FOLLOW VARCHAR(100),
    FOLLOWER VARCHAR(100)   
    
);
